name: sslcommerz_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  http: ^0.13.6
  shelf_cors_headers: ^0.1.5
  googleapis_auth: ^1.4.0
  firebase_admin: ^0.3.0+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
